# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3360a1ee7b6ff414e6def592f290554c31e36c5b8e13cac4cb9e3c6ace345fd0fc6aeec372a4e3184eb9755d4c82c16e63f307438bc5414169ecbcf89600b3e

test:
  secret_key_base: d41f8396b55f2fb8f34168cc341715f5814f550bc3ea94c2ab4d73b011784179e5bc9d9c07e4e944342a936c22e9b3fc02cff899d94d35b17501d2e8eaa7ae32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
